### ISSUE TITLE
The detail of experiment settings

### ISSUE THREAD

**Issue by Woooooody** [mklimasz/TransE-PyTorch#4]
Hi~

I run the code on FB15K dataset with 2000 epoch, and the result of hits@10 only got 1.6%。

How many epochs did you run on the report results?

**Comment by mklimasz** [comment]
Hey,
I'm not 100% sure however I would assume that default values are the ones I have used to report the results.
I reran the experiment for few epochs and after ~40 I achieved over 10.0 for hits@10.

**Comment by Woooooody** [comment]
I change the optimizer SGD to Adam, then I achieved over 43.0 for hits@10 with 100 epoch.  I don't know why there is such a big gap.

**Comment by mklimasz** [comment]
Are you sure that you are using correct FB15k? It works on default settings for me with SGD without any problem.
Can you provide any working example of the issue?

**Comment by mexiQQ** [comment]
My score for hits@10 is 10.1% with epochs equal 2000. I am changing to Adam.
