### ISSUE TITLE
different results

### ISSUE THREAD

**Issue by MarsZzh** [mklimasz/TransE-PyTorch#7]
Thanks for your contribution, I use default parameters, Hits@10 only has 33.46%, this is the problem with different OS? looking forward your reply.

**Comment by mklimasz** [comment]
Hey,
I didn't test  it on any other system than Ubuntu.
If you didn't look into other issues, there were some claims that using different optimizer helps.

**Comment by MarsZzh** [comment]
@mklimasz thanks
